project_id = "vzjsetuhituhinhxftcg"

[functions.google-calendar-auth]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.mercadopago-create-subscription]
verify_jwt = false